LibraryManagement/Models/IssueBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string book_id { get; set; } // Assuming this is the foreign key

        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }

        // Navigation property for Book
        public virtual Book Book { get; set; }
    }
}

LibraryManagement/Controllers/IssueBookController.cs
using LibraryManagement.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class IssueBookController : Controller
    {
        private LibraryManagementDBEntities1 db = new LibraryManagementDBEntities1();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetMid(int id)
        {
            var member = db.Members
                           .Where(m => m.id == id)
                           .Select(m => new { m.name })
                           .FirstOrDefault();

            return Json(member, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetBook()
        {
            var books = db.Books
                          .Select(b => new { ID = b.id, Bname = b.bname })
                          .ToList();
            return Json(books, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Save(IssueBook i)
        {
            if (ModelState.IsValid)
            {
                db.IssueBooks.Add(i);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index", i); // Return to the view with the model data if not valid
        }
    }
}

LibraryManagement/Views/IssueBook/Index.cshtml
@model LibraryManagement.Models.IssueBook





<div class="row">
    <div class="col-sm-6 offset-sm-3">
        @using (Html.BeginForm("Save", "IssueBook", FormMethod.Post))
        {
            <div class="card p-4">
                <h3 class="card-title">Issue Book</h3>

                <div class="form-group">
                    <label for="member_id">Member Id</label>
                    <input type="text" id="member_id" name="MemberId" class="form-control" placeholder="Member" required />
                </div>

                <div class="form-group">
                    <label for="mname">Name</label>
                    <input type="text" id="mname" name="MemberName" class="form-control" placeholder="Name" readonly />
                </div>

                <div class="form-group">
                    <label for="book_id">Book Name</label>
                    <select class="form-control" id="book_id" name="BookId" required>
                        <option value="">Please Select</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="issuedate">Issue Date</label>
                    <input type="date" id="issuedate" name="IssueDate" class="form-control" required />
                </div>

                <div class="form-group">
                    <label for="returndate">Return Date</label>
                    <input type="date" id="returndate" name="ReturnDate" class="form-control" required />
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Save" class="btn btn-success btn-lg" />
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/jquery-3.7.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>

    <script>
        function getMid() {
            $("#member_id").keyup(function () {
                var memberId = $("#member_id").val();
                if (memberId.length > 0) {
                    $.ajax({
                        type: 'GET',
                        url: '/IssueBook/GetMid?id=' + memberId,
                        dataType: 'json',
                        success: function (data) {
                            if (data) {
                                $("#mname").val(data.name);
                            } else {
                                $("#mname").val("Member not found");
                            }
                        },
                        error: function () {
                            alert("Error retrieving member name");
                        }
                    });
                } else {
                    $("#mname").val("");
                }
            });
        }

        function getBook() {
            $.ajax({
                type: 'GET',
                url: '/IssueBook/GetBook',
                dataType: 'json',
                success: function (data) {
                    $('#book_id').empty();
                    $('#book_id').append('<option value="">Please Select</option>');
                    $.each(data, function (i, book) {
                        $('#book_id').append($('<option>', {
                            value: book.ID,
                            text: book.Bname
                        }));
                    });
                },
                error: function (xhr, status, error) {
                    alert("Error retrieving books: " + xhr.responseText);
                }
            });
        }

        $(document).ready(function () {
            getMid();
            getBook();
        });
    </script>
}