LibraryManagement/Models/ReturnBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBook
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string book { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<int> elap { get; set; }
        public Nullable<int> fine { get; set; }
    }
}

LibraryManagement/Controllers/ReturnBookController.cs
using LibraryManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class ReturnBookController : Controller
    {
        private LibraryManagementDBEntities1 db = new LibraryManagementDBEntities1();

        // GET: ReturnBook
        public ActionResult Index()
        {
            var issuedBooks = db.IssueBooks.Select(s => new
            {
                MemberId = s.member_id,
                BookName = s.book_id, // Ensure `Book` has a `name` property in `IssueBooks`
                IssueDate = s.issuedate,
                ReturnDate = s.returndate
            }).ToList();

            ViewBag.IssuedBooks = issuedBooks;
            return View();
        }

        // Fetch details by member ID for AJAX
        public ActionResult GetMid(int id)
        {
            var memberDetails = (from s in db.IssueBooks
                                 where s.member_id == id
                                 select new
                                 {
                                     IssueDate = s.issuedate,
                                     ReturnDate = s.returndate,
                                     MemberId = s.member_id,
                                     BookName = s.book_id, // Ensure Book has a 'name' property
                                     ElapsedDays = SqlFunctions.DateDiff("day", s.returndate, DateTime.Now)
                                 }).ToList();

            return Json(memberDetails, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Save(ReturnBook returnBook)
        {
            if (ModelState.IsValid)
            {
                db.ReturnBooks.Add(returnBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index", returnBook);
        }
    }
}

LibraryManagement/Views/ReturnBook/Index.cshtml
@model LibraryManagement.Models.ReturnBook

@{
    ViewBag.Title = "Return Book";
}

<h2>Return Book</h2>
<div class="row">
    <div class="col-sm-5">
        @using (Html.BeginForm("Save", "ReturnBook", FormMethod.Post))
        {
            <div>
                <h3>Return Book</h3>
            </div>

            <div class="form-group">
                <label>Member ID</label>
                <input type="text" id="member_id" name="member_id" class="form-control" placeholder="Member ID" required />
            </div>
            <div class="form-group">
                <label>Name</label>
                <input type="text" id="mname" class="form-control" placeholder="Name" readonly />
            </div>
            <div class="form-group">
                <label>Book</label>
                <select class="form-control" id="book" name="book" required>
                    <option value="">Please Select</option>
                </select>
            </div>
            <div class="form-group">
                <label>Return Date</label>
                <input type="date" id="returnbook" name="returndate" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label>Days Elapsed</label>
                <input type="text" id="elap" name="elap" class="form-control" placeholder="Days Elapsed" readonly />
            </div>
            <div class="form-group">
                <label>Fine</label>
                <input type="text" id="fine" name="fine" class="form-control" placeholder="Fine" readonly />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>

    <script>
        function getMid() {
            $("#member_id").keyup(function () {
                var memberId = $("#member_id").val();
                if (memberId.length > 0) {
                    $.ajax({
                        type: 'GET',
                        url: '/ReturnBook/GetMid?id=' + memberId,
                        dataType: 'json',
                        success: function (data) {
                            if (data.length > 0) {
                                $("#mname").val(data[0].MemberId);
                                $("#book").empty();
                                $("#book").append($("<option>", {
                                    value: data[0].BookName,
                                    text: data[0].BookName
                                }));
                                $("#returnbook").val(new Date(data[0].ReturnDate).toISOString().split('T')[0]);

                                var elapsedDays = data[0].ElapsedDays || 0;
                                $('#elap').val(elapsedDays);
                                $('#fine').val(elapsedDays > 0 ? elapsedDays * 100 : 0);
                            } else {
                                $("#mname").val("Member not found");
                                $("#book").empty().append("<option value=''>Please Select</option>");
                                $("#returnbook").val('');
                                $('#elap').val('');
                                $('#fine').val('');
                            }
                        },
                        error: function () {
                            alert("Error retrieving member details");
                        }
                    });
                } else {
                    $("#mname").val("");
                    $("#book").empty().append("<option value=''>Please Select</option>");
                    $("#returnbook").val('');
                    $('#elap').val('');
                    $('#fine').val('');
                }
            });
        }

        $(document).ready(function () {
            getMid();
        });
    </script>
}