LibraryManagement/Controllers/AuthorController.cs
using LibraryManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class AuthorController : Controller
    {
        LibraryManagementDBEntities1 db= new LibraryManagementDBEntities1 ();
        // GET: Author
        public ActionResult Index()
        {
            var data = db.Authors.ToList();
            return View(data);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Author c)
        {
            db.Authors.Add(c);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = db.Authors.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Author c)
        {
            db.Authors.AddOrUpdate(c);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var data = db.Authors.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Delete(int id, Author c)
        {
            var data = db.Authors.Find(id);

            db.Authors.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

LibraryManagement/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManagement.Models;

namespace LibraryManagement.Controllers
{
    public class BookController : Controller
    {
        private LibraryManagementDBEntities1 db = new LibraryManagementDBEntities1();

        // GET: Book
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Author).Include(b => b.Category).Include(b => b.Publisher);
            return View(books.ToList());
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            ViewBag.auth_id = new SelectList(db.Authors, "id", "name");
            ViewBag.cat_id = new SelectList(db.Categories, "id", "catname");
            ViewBag.pub_id = new SelectList(db.Publishers, "id", "name");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,bname,cat_id,auth_id,pub_id,contents,pages,edition")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.auth_id = new SelectList(db.Authors, "id", "name", book.auth_id);
            ViewBag.cat_id = new SelectList(db.Categories, "id", "catname", book.cat_id);
            ViewBag.pub_id = new SelectList(db.Publishers, "id", "name", book.pub_id);
            return View(book);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.auth_id = new SelectList(db.Authors, "id", "name", book.auth_id);
            ViewBag.cat_id = new SelectList(db.Categories, "id", "catname", book.cat_id);
            ViewBag.pub_id = new SelectList(db.Publishers, "id", "name", book.pub_id);
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,bname,cat_id,auth_id,pub_id,contents,pages,edition")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.auth_id = new SelectList(db.Authors, "id", "name", book.auth_id);
            ViewBag.cat_id = new SelectList(db.Categories, "id", "catname", book.cat_id);
            ViewBag.pub_id = new SelectList(db.Publishers, "id", "name", book.pub_id);
            return View(book);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryManagement/Controllers/CategoryController.cs
using LibraryManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class CategoryController : Controller
    {
        LibraryManagementDBEntities1 db = new LibraryManagementDBEntities1();
        // GET: Category
        public ActionResult Index()
        {
            var data = db.Categories.ToList();
            return View(data);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category c)
        {
            db.Categories.Add(c);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = db.Categories.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Category c)
        {
            db.Categories.AddOrUpdate(c);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var data = db.Categories.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Delete(int id, Category c)
        {
            var data = db.Categories.Find(id);

            db.Categories.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
       
}

LibraryManagement/Controllers/MemberController.cs
using LibraryManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class MemberController : Controller
    {
        LibraryManagementDBEntities1 db = new LibraryManagementDBEntities1();
        // GET: Member
        public ActionResult Index()
        {
            var data = db.Members.ToList();
            return View(data);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Member c)
        {
            db.Members.Add(c);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = db.Members.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Member c)
        {
            db.Members.AddOrUpdate(c);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var data = db.Members.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Delete(int id, Member c)
        {
            var data = db.Members.Find(id);

            db.Members.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

LibraryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        /* Basic Reset */
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: Arial, sans-serif;
        }

        /* Body & Container Setup */
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            background-color: #f8f9fa;
        }

        .container-fluid {
            display: flex;
            flex: 1;
        }

        /* Sidebar Styling */
        .sidebar {
            background-color: #343a40;
            color: white;
            padding-top: 20px;
            width: 240px;
            position: fixed;
            height: 100vh;
        }

            .sidebar a {
                color: #adb5bd;
                padding: 15px 20px;
                text-decoration: none;
                display: block;
                font-size: 16px;
                font-weight: 500;
                transition: background 0.3s, color 0.3s;
            }

                .sidebar a:hover {
                    background-color: #495057;
                    color: #ffffff;
                }

            .sidebar .active {
                background-color: #007bff;
                color: #ffffff;
            }

        /* Main Content Styling */
        .main-content {
            margin-left: 240px;
            padding: 20px;
            flex-grow: 1;
            background-color: #ffffff;
            border-left: 1px solid #ddd;
        }

        /* Navbar Styling */
        .navbar {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 10px 20px;
        }

            .navbar h2 {
                font-size: 24px;
                color: #333;
                font-weight: bold;
            }

            .navbar .nav-link {
                font-size: 16px;
                font-weight: bold;
                color: #333;
            }

        /* Footer Styling */
        footer {
            padding: 15px 0;
            text-align: center;
            background-color: #f1f1f1;
            font-size: 14px;
            color: #666;
            border-top: 1px solid #ddd;
        }
    </style>
</head>

<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <h4 class="text-center">Library Management</h4>
        <a href="@Url.Action("Index", "Home")" class="active">Home</a>
        <a href="@Url.Action("Index", "Category")">Category</a>
        <a href="@Url.Action("Index", "Author")">Author</a>
        <a href="@Url.Action("Index", "Publisher")">Publisher</a>
        <a href="@Url.Action("Index", "Member")">Member</a>
        <a href="@Url.Action("Index", "Book")">Book</a>
        <a href="@Url.Action("Index", "IssueBook")">Issue Book</a>
        <a href="@Url.Action("Index", "ReturnBook")">Return Book</a>
        <br />
        <br />
        <br />
        @if (Session["UserName"] != null)
        {
            <span class="font-weight-bold text-dark mr-3">
                <i class="fas fa-user"></i> Hello, @Session["UserName"]
            </span>
            <br />
            @Html.ActionLink("Logout", "Logout", "Register", new { area = "" },
                new { @class = "nav-link text-dark font-weight-bold", onclick = "return confirm('Are you sure you want to logout?');" })
        }
        else
        {
            @Html.ActionLink("Login", "Login", "Register", new { area = "" }, new { @class = "nav-link text-dark font-weight-bold" })
        }
    </div>

    <!-- Main Content -->
    <div class="main-content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
            <h2 class="text-center">Welcome to Our Library</h2>

            @*<div class="d-flex align-items-center">
            @if (Session["UserName"] != null)
            {
                <span class="font-weight-bold text-dark mr-3">
                    <i class="fas fa-user"></i> Hello, @Session["UserName"]
                </span>
                <br/>
                @Html.ActionLink("Logout", "Logout", "Register", new { area = "" },
                    new { @class = "nav-link text-dark font-weight-bold", onclick = "return confirm('Are you sure you want to logout?');" })
            }
            else
            {
                @Html.ActionLink("Login", "Login", "Register", new { area = "" }, new { @class = "nav-link text-dark font-weight-bold" })
            }
        </div>*@
        </nav>

        <div>
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <p>&copy; @DateTime.Now.Year - Library Management System</p>
    </footer>

    <!-- Scripts -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryManagement/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - sample project</title>
    @Styles.Render("~/Content/assets/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/assets/css")

    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="~/Content/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/cs-skin-elastic.css">
     <link rel="stylesheet" href="assets/css/bootstrap-select.less"> 
    <link rel="stylesheet" href="~/Content/assets/scss/style.css">
    <link href="~/Content/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

     <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> 


    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


</head>
<body>

    <!-- Left Panel -->

    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">


            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="index.html"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>

                        @if (Session["UserName"] != null)
                        {
                        <li>
                            <span class="nav-link">Hello, @Session["UserName"]</span>
                        </li>
                    }

                        </li>

                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Category", "Index", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Author", "Index", "Author", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Publisher", "Index", "Publisher", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Member", "Index", "Member", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Book", "Index", "Book", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("IssueBook", "Index", "IssueBook", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("ReturnBook", "Index", "ReturnBook", new { area = "" }, new { @class = "nav-link" })</li>

                        @if (Session["UserName"] != null)
                        {
                            <li>
                                <span class="nav-link">Hello, @Session["UserName"]</span>
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Logout", "Logout", "Register", new { area = "" }, new { @class = "nav-link", onclick = "return confirm('Are you sure you want to logout?');" })
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Login", "Login", "Register", new { area = "" }, new { @class = "nav-link" })
                            </li>
                        }


                        @*<h3 class="menu-title">UI elements</h3>

                            <li class="menu-item-has-children dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false"><i class="menu-icon fa fa-laptop"></i>Components</a>
                                <ul class="sub-menu children dropdown-menu">
                                    <li><i class="fa fa-table"></i><a href="@Url.Action("Index", "Home")">Home</a></li>
                                    <li><i class="fa fa-table"></i><a href="@Url.Action("Index", "Customers")">Add customers</a></li>


                                </ul>
                            </li>*@



                    </ul>

                </div>
                <!-- /.navbar-collapse -->
            </nav>
        </aside>
        <!-- /#left-panel -->
        <!-- Left Panel -->
        <!-- Right Panel -->

        <div id="right-panel" class="right-panel">

            <!-- Header-->
            <header id="header" class="header" style="background-color:#343a40">

                <div class="header-menu">

                    <div class="col-sm-7">
                        <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>

                        <div class="header-left">
                            @*<button class="search-trigger"><i class="fa fa-search"></i></button>*@
                            <div class="form-inline">
                                @*<form class="search-form">
                                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..."
                                               aria-label="Search">
                                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                                    </form>*@
                            </div>
                        </div>
                    </div>
                </div>

            </header>
            <!-- /header -->
            <!-- Header-->

            <div class="breadcrumbs">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            @*<h4>username : @Session["username"].ToString()</h4>
                            <a href="@Url.Action("Logout","AdminLogin")">System LogOut</a>*@
                        </div>
                    </div>
                </div>

            </div>

            <div class="breadcrumbs">
                <div class="col-md-12">
                    <div class="page-header float-left">
                        <div class="container body-content" style="background-color:white;">
                            @RenderBody()
                            <hr />
                            <footer>
                                <p>smart Learning System 2019</p>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Panel -->

        <script src="~/Content/assets/js/vendor/jquery-2.1.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
        <script src="~/Content/assets/js/plugins.js"></script>
        <script src="~/Content/assets/js/main.js"></script>


        <script src="~/Content/assets/js/lib/chart-js/Chart.bundle.js"></script>
        <script src="~/Content/assets/js/dashboard.js"></script>
        <script src="~/Content/assets/js/widgets.js"></script>
        <script src="~/Content/assets/js/lib/vector-map/jquery.vmap.js"></script>
        <script src="~/Content/assets/js/lib/vector-map/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
        <script src="~/Content/assets/js/lib/vector-map/country/jquery.vmap.world.js"></script>
        @*<script>
                (function ($) {
                    "use strict";

                    jQuery('#vmap').vectorMap({
                        map: 'world_en',
                        backgroundColor: null,
                        color: '#ffffff',
                        hoverOpacity: 0.7,
                        selectedColor: '#1de9b6',
                        enableZoom: true,
                        showTooltip: true,
                        values: sample_data,
                        scaleColors: ['#1de9b6', '#03a9f5'],
                        normalizeFunction: 'polynomial'
                    });
                })(jQuery);
            </script>*@

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
      
        <script src="~/Scripts/alertify.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        @Scripts.Render("~/Content/Metronic/global/plugins/jquery.min.js")
        @RenderSection("scripts", required: false)

    </body>
</html>